### ISSUE TITLE
Cannot Get Peatio front-end up

### ISSUE THREAD

**Issue by Mishul-G** [rubykube/workbench#23]
So I have successfully setup the entire thing, I have laid down the callback in barong and configured it appropriately. 

At this point, I cannot access the front-end for peatio. After running "docker-compose up -d peatio", once I go to peatio:8000 or localhost:8000 (or peatio:3000/localhost:3000) I get the "site cannot be reached" error. 

I have attached the image of what I get after running "docker-compose ps" to see what all ports docker is interacting with. The Peatio site seems to be up on 0.0.0.0:8000 and then it exits. Would appreciate help in any this.

![28342230_10215931999352844_1312746501_o](https://user-images.githubusercontent.com/35405917/36512375-c5b0f568-172f-11e8-843d-1935816150ae.png)

**Comment by bernardpeh** [comment]
had the same problem.

docker-compose logs peatio reveals
```
Attaching to peatioworkbench_peatio_1
peatio_1          | Puma starting in single mode...
peatio_1          | * Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
peatio_1          | * Min threads: 5, max threads: 5
peatio_1          | * Environment: development
peatio_1          | ! Unable to load application: Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
peatio_1          | bundler: failed to load command: puma (/opt/vendor/bundle/ruby/2.5.0/bin/puma)
peatio_1          | /opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_ADDRESS". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_OAUTH2_REDIRECT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
peatio_1          |   /home/app/config/initializers/assets.rb:29:in `chdir'
peatio_1          |   /home/app/config/initializers/assets.rb:29:in `<top (required)>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
peatio_1          |   /home/app/config/environment.rb:5:in `<top (required)>'
peatio_1          |   config.ru:3:in `require'
peatio_1          |   config.ru:3:in `block in <main>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
peatio_1          |   config.ru:in `new'
peatio_1          |   config.ru:in `<main>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
peatio_1          | Puma starting in single mode...
peatio_1          | * Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
peatio_1          | * Min threads: 5, max threads: 5
peatio_1          | * Environment: development
peatio_1          | ! Unable to load application: Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
peatio_1          | bundler: failed to load command: puma (/opt/vendor/bundle/ruby/2.5.0/bin/puma)
peatio_1          | /opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_ADDRESS". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_OAUTH2_REDIRECT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
peatio_1          |   /home/app/config/initializers/assets.rb:29:in `chdir'
peatio_1          |   /home/app/config/initializers/assets.rb:29:in `<top (required)>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
peatio_1          |   /home/app/config/environment.rb:5:in `<top (required)>'
peatio_1          |   config.ru:3:in `require'
peatio_1          |   config.ru:3:in `block in <main>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
peatio_1          |   config.ru:in `new'
peatio_1          |   config.ru:in `<main>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
peatio_1          | Puma starting in single mode...
peatio_1          | * Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
peatio_1          | * Min threads: 5, max threads: 5
peatio_1          | * Environment: development
peatio_1          | ! Unable to load application: Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
peatio_1          | bundler: failed to load command: puma (/opt/vendor/bundle/ruby/2.5.0/bin/puma)
peatio_1          | /opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_ADDRESS". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_OAUTH2_REDIRECT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
peatio_1          |   /home/app/config/initializers/assets.rb:29:in `chdir'
peatio_1          |   /home/app/config/initializers/assets.rb:29:in `<top (required)>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
peatio_1          |   /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
peatio_1          |   /home/app/config/environment.rb:5:in `<top (required)>'
peatio_1          |   config.ru:3:in `require'
peatio_1          |   config.ru:3:in `block in <main>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
peatio_1          |   config.ru:in `new'
peatio_1          |   config.ru:in `<main>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
peatio_1          |   /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
```

**Comment by myujang** [comment]
@bernardpeh can you show me 'docker logs peatioworkbench_peatio_1'
i encounter this issue also before.

**Comment by bernardpeh** [comment]
> docker logs peatioworkbench_peatio_1

Puma starting in single mode...
* Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_ADDRESS". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_OAUTH2_REDIRECT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
  /home/app/config/initializers/assets.rb:29:in `chdir'
  /home/app/config/initializers/assets.rb:29:in `<top (required)>'
! Unable to load application: Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
bundler: failed to load command: puma (/opt/vendor/bundle/ruby/2.5.0/bin/puma)
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
  /home/app/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
  /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
  /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
Puma starting in single mode...
* Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
! Unable to load application: Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
bundler: failed to load command: puma (/opt/vendor/bundle/ruby/2.5.0/bin/puma)
/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_ADDRESS". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_OAUTH2_REDIRECT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
  /home/app/config/initializers/assets.rb:29:in `chdir'
  /home/app/config/initializers/assets.rb:29:in `<top (required)>'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
  /home/app/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
  /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
  /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
Puma starting in single mode...
* Version 3.11.0 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
! Unable to load application: Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
bundler: failed to load command: puma (/opt/vendor/bundle/ruby/2.5.0/bin/puma)
/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_ADDRESS". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "SMTP_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "OAUTH2_SIGN_IN_PROVIDER". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_ID". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_CLIENT_SECRET". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_DOMAIN". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "BARONG_OAUTH2_REDIRECT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)Errno::ENOENT: No such file or directory @ dir_chdir - vendor/assets/yarn_components
  /home/app/config/initializers/assets.rb:29:in `chdir'
  /home/app/config/initializers/assets.rb:29:in `<top (required)>'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
  /home/app/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
  /opt/vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
  /opt/vendor/bundle/ruby/2.5.0/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
  /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
  /opt/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'

**Comment by tigwyk** [comment]
I fixed this by manually running the following:
`docker-compose run --rm peatio bin/rake yarn:install assets:precompile`

You should then be able to follow the rest of the instructions to bring the front end up and it should stay up instead of throwing errors now.

**Comment by ZohairZaman** [comment]
Followed the guide and did all the instructions; I get to the following error at this point when i try to access peatio:8000 (or localhost:8000) locally. Barong seems to be working fine. 
<img width="1346" alt="screen shot 2018-02-22 at 23 09 50" src="https://user-images.githubusercontent.com/14031784/36578912-c5b89812-1825-11e8-91c5-1a45e92a05d6.png">

**Comment by Mishul-G** [comment]
@tigwyk Did you have the problem described by @ZohairZaman  above? We have been stuck on this for a while. Running the command described on peatio:8000 does not fix this issue. Thanks for all your help

**Comment by tigwyk** [comment]
@Mishul-G I did not receive the error regarding a pending migration. Once I manually ran the yarn:install rake task my app has actually been working fine. Definitely no database issues. In the docker-compose file I changed peatio and barong to reference the public facing hostname of my server. I can rebuild the peatio and barong images without any further issues.

The only problem I face now is not being able to verify my account in barong (or mark the account as verified somehow in peatio) so I can't test deposits/withdrawls.

**Comment by Mishul-G** [comment]
@tigwyk Thanks for your insight. We have set it up on multiple machines on Ubuntu & OSX and are getting the same migration error in both. 

I tried those commands but have not gotten further. I will look into how to get barong verified will let you know if I figure the solution. Thanks for your help.

**Comment by gulnazkassym** [comment]
@Mishul-G Hello. Have the same issue. Did you find solution?

**Comment by Mishul-G** [comment]
You email me or add on skype - mgupta14@illinois.edu for installations & consultation. We have deployed live exchanges

**Comment by Gensia** [comment]
What was the fix?
